web1:
  name: openCart
  php_extensions:
    - mysql
    - mcrypt
    - curl
    - zip
    - gd
  shared_writable_dirs:
    - system/cache/
    - system/logs/
    - download/
    - image/
    - install/
  after_deploy:
    - "mkdir image/cache; cp -rv pagoda/image/cache/* image/cache/"
    - "mkdir image/data; cp -rv pagoda/image/data/* image/data/"
    - "cp -rv pagoda/download/* download/"
    - "cp -rv pagoda/vqmod/* vqmod/"
    - "cp -rv pagoda/install/* install/"
db1:
  name: openCart